### ISSUE TITLE
Promote plugins from the home page

### ISSUE THREAD

**Issue by paulilli** [qunitjs/qunitjs.com#100]
QUnit has a few really nice/plugins but I think we should promote it more and encourage more people to build/use them.

On the homepage there's totally no emphasize on the fact that qunit plugins/themes exist, while I do consider it an important feature of qunit. Any thoughts are welcome?

**Comment by paulilli** [comment]
I'm also talking about themes. I always hated QUnit because it was ugly, and just explored that it has themes. Why didn't anybody told me yet :p

**Comment by scottgonzalez** [comment]
> On the homepage there's totally no emphasize on the fact that qunit plugins/themes exist

Well, there's a link in the Learn More section. Did you have anything specific in mind? Perhaps someone from @jquery/content has some ideas.

**Comment by agcolom** [comment]
Yes, I had a look at the site and found the theming by searching "theme". We could add a theming menu item on the api docs like we have for jQuery UI and Mobile and/or a Themes tab on the homepage... 

However, I'm not sure whether we actually can as all the themes are in private repos. Would that be problem?

**Comment by Krinkle** [comment]
There is a "Plugins" page (since 2014), and it's currently linked from main navigation atop every page, as well as from the "Learn More" paragraph on the home page.

<img width="701" alt="screen shot 2018-05-02 at 00 48 35" src="https://user-images.githubusercontent.com/156867/39498856-922a8fca-4da2-11e8-88dd-122c5f9f74ce.png">

The [new site](https://github.com/qunitjs/qunitjs.github.io) also mentions "Extendible" on the home page. Which seems like all-in-all would be enough to close this issue.

<img width="1127" alt="screen shot 2018-05-02 at 00 48 19" src="https://user-images.githubusercontent.com/156867/39498850-87bb3cb0-4da2-11e8-99c7-0587bf70a918.png">

Perhaps a few final notes before we close it:

* [ ] Make sure "Plugins" guide (on the new site) is linked from the "Extensible" blurb on the home page.
* [ ] Consider linking "Plugins" form the main nav (inside of inside "Guides").
* [ ] Close this issue once the site is live on the main domain :)
