### ISSUE TITLE
Clean up plugins list

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunitjs.com#102]
We list several projects that are likely not working anymore, are useless by now or have some other issue. For example, both pavlov and specit haven't been updated in several years. qunit-helpful is very limited value since we improve output for the `ok` assertion. qunit-once goes against the recommendation to keep tests atomic.

**Comment by arschmitz** [comment]
:+1: no way to make hard guidelines on something like this, but good to review any curated type list like this once in a while.

**Comment by JamesMGreene** [comment]
Instead of removing "qunit-helpful" just yet, perhaps we should just add a note that it is only relevant for QUnit versions `< x.y.z`.

Personally, I'd leave "qunit-once" on the list as I think it offers legitimate value [and can be used atomically] for the right scenarios.

SpecIt/Pavlov may be fine without updating as our primary API entry points really hasn't changed much in years either. Sure, they won't necessarily be using the latest best practices (which would potentially make them incompatible with older versions, to be fair) but I'd imagine they would still work with any QUnit `1.x` versions. I'd suggest we assess each before removing it.

**Comment by JamesMGreene** [comment]
Moreover, I'd be down for just using an NPM keyword search for "qunit-plugin" and being done with it. :wink:

If we wanted curated plugins, we could create a "qunit-contrib"/'qunit-auxiliary" organization to own the blessed ones.

**Comment by leobalter** [comment]
> Moreover, I'd be down for just using an NPM keyword search for "qunit-plugin" and being done with it. :wink:

:+1: 

For curated plugins I would stick with *qunit-contrib* to make it consistent with grunt-contrib plugins.

**Comment by Krinkle** [comment]
Closing. The new site bases its plugins page on an npm search for `keywords:qunit-plugin` (at build-time, not client-side). We could consider a different keyword, but it seems sensible to stick for the moment with the one actually used by plugins. Let's file a new issue in the main repo for changing the keyword?
