### ISSUE TITLE
Who uses QUnit

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunitjs.com#163]
A page akin to <https://gruntjs.com/who-uses-grunt> to see which projects are using QUnit, with links to examples of their integration to learn from and peek into.

Using this gather a dozen or so to start with.

**Comment by Krinkle** [comment]
<https://fluidproject.org/>

> Fluid is an open, collaborative project to improve the user experience and inclusiveness of open source software.

Their [Infusion](https://github.com/fluid-project/infusion) uses QUnit throughout using an integration layer called [node-jqunit](https://github.com/fluid-project/node-jqunit).

/cc @jobara Hi, I noticed you are an active developer on the project. Do you think it would be okay for us to mention the Fluid project with a link on our website?

I noticed the project currently uses an embedded copy of QUnit 1.12. Do let us know if you'd like any help upgrading (or [chat with us](https://gitter.im/qunitjs/qunit)). Always happy to help!

**Comment by jobara** [comment]
@Krinkle should be okay to mention our project on your site. Thanks for asking. Regarding the embedded version of QUnit, we'll try to write up some info about why we are using that version and share it back with you.

**Comment by amb26** [comment]
Hi @Krinkle - our integration with the ancient QUnit made a few patches to deal with some test framework startup races caused by the old setTimeout(xxxx, 13) system. It's very likely that these are resolved or at least behave differently in newer QUnits but when I poked around a few years ago I couldn't easily find the equivalent sites to inspect for fixes, so it seems the logic was substantially reworked after 1.x. We have an in-house testing framework that is fairly tightly coupled to the internals of the old QUnit. It would be nice to upgrade but would probably need a fair amount of dedicated time from people familiar with the internals of both systems - we hope to get around to it someday. Thanks for the note and the offer of help! We're happy to be cited as users happily benefitting from the system but I imagine our integration is not something we would want others to learn from.

**Comment by Krinkle** [comment]
<https://doc.wikimedia.org/>

> Wikimedia Foundation, the non-profit behind Wikipedia and many other free knowledge and open source projects.

Uses QUnit for the featured [VisualEditor](https://github.com/wikimedia/VisualEditor/#readme) ([examples](https://github.com/wikimedia/VisualEditor/tree/6eac66f9cd28fcdf1b084126fcf04b340858c30b/tests)) and [MediaWiki](https://www.mediawiki.org) ([example](https://github.com/wikimedia/mediawiki/tree/1.34.2/tests/qunit/suites/resources/mediawiki)) projects, as well as in most other projects.

**Comment by Krinkle** [comment]
<https://wordpress.org/> ([test suite](https://github.com/WordPress/wordpress-develop/tree/5.5.0/tests/qunit))

> WordPress is open source software you can use to create a beautiful website, blog, or app.

**Comment by trentmwillis** [comment]
As mentioned on the site already, many Ember projects use QUnit. So probably lots of potential examples from that community.

**Comment by Krinkle** [comment]
@smcclure15 Hi - I was looking for a MathWorks project to list as example but couldnt't find any. Perhaps I'm looking it the wrong place?

**Comment by smcclure15** [comment]
All of MathWorks' src/test is within internal SCM systems and private.
I can say that we have on the order of 5K test files amounting to ~36K QUnit testpoints.

I can get you other stats/patterns as needed, but I need to respect confidentiality.

**Comment by Krinkle** [comment]
@smcclure15 Nice, those are some cool stats! I do see a lots of open-source projects by MathWorks on GitHub under @mathworks, @mathworks-robotics, @mathworks-simbiology etc., but couldn't find any frontend or Node projects that use QUnit. Perhaps in the future :)

Feel free to submit a patch here anytime, I'd love to feature a MathWorks open-source project that utilises QUnit.
